name: Kuvatuuli
favicon: null
layout_spectrum: 0.23077
typography_spectrum: 0.64593
title: lapsi- ja koirakuvaukset suurella sydämellä
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4c8d1'
    - '#635258'
    - '#918c92'
    - '#6b0b16'
    - '#da5071'
  brandStrength: 1
  lightness: 0.5832359129562974
  saturation: 0.4618531889282167
  rhythmicContrast: 0.6029819049872458
purpose: []
